/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import Logic.AdminLoginManager; 
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import gui.AdminDashboardGUI;

/**
 *
 * @author airi
 */
public class AddStudentForm extends javax.swing.JFrame {
    
    private final AdminLoginManager loginManager = new AdminLoginManager();

    /**
     * Creates new form Registration
     */
    public AddStudentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        firstName3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        firstName5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        firstName7 = new javax.swing.JTextField();
        firstName8 = new javax.swing.JTextField();
        firstName9 = new javax.swing.JTextField();
        firstName10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(314, 314, 314))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Student Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Phone Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setText("Student Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, 20));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setText("Date Of Birth");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        firstName3.setBackground(new java.awt.Color(234, 239, 249));
        firstName3.setText("MM/DD/YYYY");
        firstName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName3ActionPerformed(evt);
            }
        });
        jPanel1.add(firstName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 350, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setText("ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        firstName5.setBackground(new java.awt.Color(234, 239, 249));
        firstName5.setText("Last Name");
        firstName5.setToolTipText("");
        firstName5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName5ActionPerformed(evt);
            }
        });
        jPanel1.add(firstName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 170, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(93, 34, 250));
        jLabel8.setText("Student Registration Form ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        firstName7.setBackground(new java.awt.Color(238, 238, 238));
        firstName7.setToolTipText("");
        firstName7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName7ActionPerformed(evt);
            }
        });
        jPanel1.add(firstName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 350, -1));

        firstName8.setBackground(new java.awt.Color(234, 239, 249));
        firstName8.setText("First Name");
        firstName8.setToolTipText("");
        firstName8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName8ActionPerformed(evt);
            }
        });
        jPanel1.add(firstName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 170, -1));

        firstName9.setBackground(new java.awt.Color(238, 238, 238));
        firstName9.setToolTipText("");
        firstName9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName9ActionPerformed(evt);
            }
        });
        jPanel1.add(firstName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 170, -1));

        firstName10.setBackground(new java.awt.Color(234, 239, 249));
        firstName10.setToolTipText("");
        firstName10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName10ActionPerformed(evt);
            }
        });
        jPanel1.add(firstName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 350, -1));

        jButton2.setBackground(new java.awt.Color(93, 34, 250));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add Student");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 140, 30));
        jButton2.setOpaque(true);
        jButton2.setContentAreaFilled(true);
        jButton2.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstName5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName5ActionPerformed

    private void firstName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName3ActionPerformed

    private void firstName7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName7ActionPerformed

    private void firstName8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName8ActionPerformed

    private void firstName9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName9ActionPerformed

    private void firstName10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String usernameText = username.getText().trim();
        String passwordText = new String(password.getPassword());

        if(usernameText.isEmpty() || passwordText.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Invalid login.");
            return;
        }

        new Thread(() -> {
            boolean success = loginManager.validateAdminLogin(usernameText, passwordText);

            SwingUtilities.invokeLater(() -> {
                if(success) {
                    JOptionPane.showMessageDialog(this, "Login successful!");
                    openAdminDashboard(); // another JFrame
                    this.dispose(); // close login
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid ID or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
                }
            });
        }).start();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudentForm().setVisible(true);
            }
        });
    }
    
    private void openAdminDashboard() 
    {
        AdminDashboardGUI dashboard = new AdminDashboardGUI(); // make this JFrame class
        dashboard.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firstName10;
    private javax.swing.JTextField firstName3;
    private javax.swing.JTextField firstName5;
    private javax.swing.JTextField firstName7;
    private javax.swing.JTextField firstName8;
    private javax.swing.JTextField firstName9;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
