/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import Logic.AdminLoginManager; 
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import gui.AdminDashboardGUI;
import Logic.IDGenerator;

/**
 *
 * @author airi
 */
public class AddStudentForm extends javax.swing.JFrame {
    
    private final AdminLoginManager loginManager = new AdminLoginManager();

    /**
     * Creates new form Registration
     */
    public AddStudentForm() {
        initComponents();
        
        String username = IDGenerator.generateUsername();
        
        String studentID = IDGenerator.generateID();
        IDTextField.setText(studentID);
        
        //disable editing for ID
        IDTextField.setEditable(false);
        IDTextField.setEnabled(false);
        
        
        
        String email = username + "@school.co.nz";
        studentEmailTextField. setText(email);
        
        //disable editing for email
        studentEmailTextField.setEditable(false);  
        studentEmailTextField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentNameLabel = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JLabel();
        StudentEmailLabel = new javax.swing.JLabel();
        DateOfBirthLabel = new javax.swing.JLabel();
        DOBTextField = new javax.swing.JTextField();
        IDLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        studentEmailTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        IDTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(314, 314, 314))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 30));

        studentNameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        studentNameLabel.setText("Student Name");
        jPanel1.add(studentNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        PhoneNumberLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        PhoneNumberLabel.setText("Phone Number");
        jPanel1.add(PhoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        StudentEmailLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        StudentEmailLabel.setText("Student Email");
        jPanel1.add(StudentEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, 20));

        DateOfBirthLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        DateOfBirthLabel.setText("Date Of Birth");
        jPanel1.add(DateOfBirthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        DOBTextField.setBackground(new java.awt.Color(234, 239, 249));
        DOBTextField.setText("MM/DD/YYYY");
        DOBTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(DOBTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 350, -1));

        IDLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        IDLabel.setText("ID");
        jPanel1.add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        lastNameTextField.setBackground(new java.awt.Color(234, 239, 249));
        lastNameTextField.setText("Last Name");
        lastNameTextField.setToolTipText("");
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 170, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(93, 34, 250));
        jLabel8.setText("Student Registration");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        studentEmailTextField.setBackground(new java.awt.Color(238, 238, 238));
        studentEmailTextField.setToolTipText("");
        studentEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentEmailTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(studentEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 350, -1));

        firstNameTextField.setBackground(new java.awt.Color(234, 239, 249));
        firstNameTextField.setText("First Name");
        firstNameTextField.setToolTipText("");
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 170, -1));

        IDTextField.setBackground(new java.awt.Color(238, 238, 238));
        IDTextField.setToolTipText("");
        IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(IDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 170, -1));

        phoneNumberTextField.setBackground(new java.awt.Color(234, 239, 249));
        phoneNumberTextField.setToolTipText("");
        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(phoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 350, -1));

        jButton2.setBackground(new java.awt.Color(93, 34, 250));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add Student");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 140, 30));
        jButton2.setOpaque(true);
        jButton2.setContentAreaFilled(true);
        jButton2.setBorderPainted(false);

        jButtonBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void DOBTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBTextFieldActionPerformed

    private void studentEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentEmailTextFieldActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldActionPerformed

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String id = IDTextField.getText().trim();
    String firstName = firstNameTextField.getText().trim();
    String lastName = lastNameTextField.getText().trim();
    String dob = DOBTextField.getText().trim();
    String phone = phoneNumberTextField.getText().trim();
    String email = studentEmailTextField.getText().trim();
    
    String username = IDGenerator.generateUsername();
    String defaultPassword = "defaultpass";
    

    // validation that all text fields are filled
    if ( firstName.isEmpty() || lastName.isEmpty() || dob.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all required fields.");
        return;
    }

    // create student
    Logic.Registration registration = new Logic.Registration();
    boolean success = registration.createAccount(
            
            id,
            username,
            defaultPassword,
            firstName,
            lastName,
            email,
            dob, 
            phone,
            "student"     
    );
            
            

    if (success) {
        JOptionPane.showMessageDialog(this, "Student added successfully!");
        openAdminDashboard();
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Failed to add student.");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        AdminDashboardGUI dashboard = new AdminDashboardGUI();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudentForm().setVisible(true);
            }
        });
    }
    
    private void openAdminDashboard() 
    {
        AdminDashboardGUI dashboard = new AdminDashboardGUI(); // make this JFrame class
        dashboard.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOBTextField;
    private javax.swing.JLabel DateOfBirthLabel;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JLabel StudentEmailLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JTextField studentEmailTextField;
    private javax.swing.JLabel studentNameLabel;
    // End of variables declaration//GEN-END:variables
}
