/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dataAccess.StudentData;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import gui.AddStudentForm;
import gui.AdminLoginGUI;

import java.awt.Color;
import javax.swing.JTextField;
/**
 *
 * @author airi
 */
public class AdminDashboardGUI extends javax.swing.JFrame 
{

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboardGUI() {
        initComponents();
    
        textFieldOnClick(searchField, "Search");
        loadStudentTable(); 
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        buttonLogOut = new javax.swing.JButton();
        jButtonCourses = new javax.swing.JButton();
        jButtonDashboard1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        searchField = new javax.swing.JTextField();
        buttonAddStudent1 = new javax.swing.JButton();
        buttonRemoveStudent1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(314, 314, 314))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonLogOut.setText("Log Out");
        buttonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogOutActionPerformed(evt);
            }
        });

        jButtonCourses.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButtonCourses.setText("Courses");
        jButtonCourses.setBorder(null);
        jButtonCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoursesActionPerformed(evt);
            }
        });

        jButtonDashboard1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButtonDashboard1.setText("Dashboard");
        jButtonDashboard1.setBorder(null);
        jButtonDashboard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDashboard1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonDashboard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(buttonLogOut)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButtonDashboard1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCourses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                .addComponent(buttonLogOut)
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 510));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("View Students");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID ", "Name", "Date Of Birth", "Email", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 650, 370));

        searchField.setEditable(false);
        searchField.setForeground(new java.awt.Color(153, 153, 153));
        searchField.setText("Search");
        searchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFieldMouseClicked(evt);
            }
        });
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        jPanel1.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 640, -1));

        buttonAddStudent1.setText("Add Student");
        buttonAddStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddStudent1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAddStudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 126, -1));

        buttonRemoveStudent1.setText("Remove Student");
        buttonRemoveStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveStudent1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRemoveStudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogOutActionPerformed
       int userConfirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm Log Out", JOptionPane.YES_NO_OPTION);

       System.out.println("Logout button pressed");
        if (userConfirm != JOptionPane.YES_OPTION) return;

        this.dispose();

        AdminLoginGUI loginGUI = new AdminLoginGUI();

        loginGUI.setVisible(true);
    }//GEN-LAST:event_buttonLogOutActionPerformed

    private void buttonAddStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddStudent1ActionPerformed
        // TODO add your handling code here:
  
        AddStudentForm addForm = new AddStudentForm();
        addForm.setVisible(true);   
        
    }//GEN-LAST:event_buttonAddStudent1ActionPerformed

    private void buttonRemoveStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveStudent1ActionPerformed
        
    int selected = studentTable.getSelectedRow();
    if (selected == -1) {
        JOptionPane.showMessageDialog(this, "Please select a student to remove.");
        return;
    }

    String userID = studentTable.getValueAt(selected, 0).toString();

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to remove this student?",
        "Confirm Removal",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    StudentData studentData = new StudentData();
    boolean success = studentData.deleteStudent(userID);

    if (success) {
        JOptionPane.showMessageDialog(this, "Student has been removed successfully.");
        loadStudentTable(); // refresh table properly
    } else {
        JOptionPane.showMessageDialog(this, "Failed to remove student. Check database constraints.");
    }

    }//GEN-LAST:event_buttonRemoveStudent1ActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        String searchText = searchField.getText().trim().toLowerCase();
        
        if(searchText.isEmpty())
        {
            loadStudentTable();
            return;
        }
        
        //temporary model to store search results
        
        DefaultTableModel model = (DefaultTableModel) studentTable.getModel();
        DefaultTableModel filtered = new DefaultTableModel(new Object[] {"ID", "Username", "First Name", "Last Name", "Major", "Email", "Phone", "DOB"}, 0);
        
        //loop through rows and att matching to filtered model
        
        for (int i = 0; i < model.getRowCount(); i++) 
    {
        String id = model.getValueAt(i, 0).toString().toLowerCase();
        String username = model.getValueAt(i, 1).toString().toLowerCase();
        String firstName = model.getValueAt(i, 2).toString().toLowerCase();
        String lastName = model.getValueAt(i, 3).toString().toLowerCase();
        String fullName = firstName + " " + lastName; 
                
       
            
          if (id.contains(searchText) || username.contains(searchText) || firstName.contains(searchText) || lastName.contains(searchText) || fullName.contains(searchText)) 
{
            filtered.addRow(new Object[]
            {
                model.getValueAt(i, 0),
                model.getValueAt(i, 1),
                model.getValueAt(i, 2),
                model.getValueAt(i, 3),
                model.getValueAt(i, 4),
                model.getValueAt(i, 5),
                model.getValueAt(i, 6),
                model.getValueAt(i, 7)
            });
        }
    }

    studentTable.setModel(filtered);


        
        
                
    }//GEN-LAST:event_searchFieldActionPerformed

    private void jButtonCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCoursesActionPerformed

    private void jButtonDashboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDashboard1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDashboard1ActionPerformed

    private void searchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFieldMouseClicked
        
    }//GEN-LAST:event_searchFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {

                new AdminDashboardGUI().setVisible(true);

            }
        });
    }
    
   private void loadStudentTable()
{
    StudentData studentData = new StudentData();
    studentTable.setModel(studentData.getAllStudentsTable());
}
   
   // helper method coded with ChatGPT so that textfield shows placeholder text until user clicks to type
   private void textFieldOnClick(JTextField field, String placeholder)
   {
       field.setEditable(false);
       field.setText(placeholder);
        field.setForeground(Color.GRAY);

     field.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (!field.isEditable()) {
                field.setEditable(true);
                field.setText("");
                field.setForeground(Color.BLACK);
            }
        }
    });
   }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddStudent1;
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JButton buttonRemoveStudent1;
    private javax.swing.JButton jButtonCourses;
    private javax.swing.JButton jButtonDashboard1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable studentTable;
    // End of variables declaration//GEN-END:variables


}