/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dataAccess.StudentData;

import java.sql.Connection;
import java.sql.SQLException;
import dataAccess.CourseData; 
import Database.DatabaseManager;
import model.Course;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import java.awt.*;
import java.util.List;

/**
 *
 * @author kiandrasin
 */
public class StudentDetailsGUI extends javax.swing.JFrame {

   
    private String studentId;
    
    
    /**
     * Creates new form StudentDetailsGUI
     */
    public StudentDetailsGUI(String studentId) 
    {
        this.studentId = studentId;
        initComponents();
        loadStudentDetails();
        
    jTextFieldStudentID.setEditable(false);
    jTextFieldStudentName.setEditable(false);
    jTextFieldStudentEmail.setEditable(false);
    
     loadEnrolledCourses();

    }

    
  private void loadStudentDetails() {
    StudentData studentData = new StudentData();
    try {
        var student = studentData.getStudentById(studentId);
        jTextFieldStudentID.setText(student.getID());
        jTextFieldStudentName.setText(student.getFirstName() + " " + student.getLastName());
        jTextFieldStudentEmail.setText(student.getEmail());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Failed to load student details: " + e.getMessage());
    }
}
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentName = new javax.swing.JLabel();
        studentID = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        jTextFieldStudentName = new javax.swing.JTextField();
        jTextFieldStudentID = new javax.swing.JTextField();
        jTextFieldStudentEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        removeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jLabel1)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 30));

        studentName.setText("Name:");
        jPanel1.add(studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, 20));

        studentID.setText("Student ID:");
        jPanel1.add(studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, 20));

        Email.setText("Email:");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, 20));

        jTextFieldStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStudentNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));
        jPanel1.add(jTextFieldStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));
        jPanel1.add(jTextFieldStudentEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        coursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Credit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(coursesTable);
        if (coursesTable.getColumnModel().getColumnCount() > 0) {
            coursesTable.getColumnModel().getColumn(0).setResizable(false);
            coursesTable.getColumnModel().getColumn(1).setResizable(false);
            coursesTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 510, 270));

        removeButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        removeButton.setText("Remove Course");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));

        addButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        addButton.setText("Add Course");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 479, -1, 30));

        jLabel2.setText("Enrolled Courses");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    
        dialog.setVisible(true);

    Course selected = dialog.getSelectedCourse();
    if (selected != null) {
        JOptionPane.showMessageDialog(this, "Added course: " + selected.getCourseName());
    }
    
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeButtonActionPerformed

    private void jTextFieldStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStudentNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDetailsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JButton addButton;
    private javax.swing.JTable coursesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldStudentEmail;
    private javax.swing.JTextField jTextFieldStudentID;
    private javax.swing.JTextField jTextFieldStudentName;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel studentID;
    private javax.swing.JLabel studentName;
    // End of variables declaration//GEN-END:variables

    private void loadEnrolledCourses() {
    try {
        CourseData courseData = new CourseData(DatabaseManager.getConnection());
        List<Course> enrolled = courseData.getCoursesByStudentId(studentId);

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Course ID", "Course Name", "Credits"});

        for (Course c : enrolled) {
            model.addRow(new Object[]{c.getCourseID(), c.getCourseName(), c.getCredits()});
        }

        coursesTable.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Failed to load courses: " + e.getMessage());
    }

}

    private void addCourseAction() {
    try {
        CourseData courseData = new CourseData(DatabaseManager.getConnection());

        // Example: choose the first course from all courses that student is not enrolled in
        List<Course> allCourses = courseData.getAllCourse();
        List<Course> enrolled = courseData.getCoursesByStudentId(studentId);

        Course toAdd = null;
        for (Course c : allCourses) {
            boolean already = enrolled.stream().anyMatch(ec -> ec.getCourseID().equals(c.getCourseID()));
            if (!already) {
                toAdd = c;
                break;
            }
        }

        if (toAdd != null) {
            courseData.enrollStudent(studentId, toAdd.getCourseID());
            JOptionPane.showMessageDialog(this, "Enrolled in: " + toAdd.getCourseName());
            loadEnrolledCourses();
        } else {
            JOptionPane.showMessageDialog(this, "No available courses to add");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Failed to add course: " + e.getMessage());
    }
}        

    private void removeCourseAction() {
    int selectedRow = coursesTable.getSelectedRow();
    if (selectedRow >= 0) {
        String courseId = (String) coursesTable.getValueAt(selectedRow, 0);
        try {
            CourseData courseData = new CourseData(DatabaseManager.getConnection());
            courseData.removeEnrollment(studentId, courseId);
            JOptionPane.showMessageDialog(this, "Removed course successfully");
            loadEnrolledCourses();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Failed to remove course: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a course to remove");
    }
} 

}
